# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\x11kubeedge.schedule\"a\n\x07Request\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x12\n\narrivetime\x18\x02 \x01(\x03\x12\x10\n\x08\x64\x65\x61\x64line\x18\x03 \x01(\x03\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\x01\x12\x10\n\x08hostname\x18\x05 \x01(\t\"-\n\nDeployment\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\">\n\x08Response\x12\x32\n\x0b\x64\x65ployments\x18\x01 \x03(\x0b\x32\x1d.kubeedge.schedule.Deployment2P\n\tScheduler\x12\x43\n\x08Schedule\x12\x1a.kubeedge.schedule.Request\x1a\x1b.kubeedge.schedule.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=38
  _globals['_REQUEST']._serialized_end=135
  _globals['_DEPLOYMENT']._serialized_start=137
  _globals['_DEPLOYMENT']._serialized_end=182
  _globals['_RESPONSE']._serialized_start=184
  _globals['_RESPONSE']._serialized_end=246
  _globals['_SCHEDULER']._serialized_start=248
  _globals['_SCHEDULER']._serialized_end=328
# @@protoc_insertion_point(module_scope)
